apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-queries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eeg-app
      component: db-queries
  template:
    metadata:
      labels:
        app: eeg-app
        component: db-queries
    spec:
      containers:
      - name: db-queries
        image: fberton98/db_saving:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        resources:
          limits: # max quantity of resources that container can use, otherwise --> throttled
            cpu: 400m
          requests: # guaranteed resources for this container
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: db-queries-service
  labels:
    app: eeg-app
    component: db-queries
spec:
  selector:
    app: eeg-app
    component: db-queries
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-queries-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50    # target: 50% use of CPU by POD
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-queries-deployment