apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-queries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eeg-app
      component: db-queries
  template:
    metadata:
      labels:
        app: eeg-app
        component: db-queries
    spec:
      containers:
      - name: db-queries
        image: fberton98/db_saving:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: db-queries-app-service
  labels:
    app: eeg-app
    component: db-queries
spec:
  selector:
    app: eeg-app
    component: db-queries
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
