apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
  namespace: default
spec:
  rules:
  - host: healtcare_cluster
    http:
      paths:
      - path: /new-eeg-data
        pathType: Prefix
        backend:
          service:
            name: new-eeg-data-endpoint-service
            port:
              number: 80
