apiVersion: apps/v1
kind: Deployment
metadata:
  name: epilepsy-prediction-deployment${APPENDSTRING}
spec:
  selector:
    matchLabels:
      app: eeg-app
      component: epilepsy-prediction${APPENDSTRING}
  template:
    metadata:
      labels:
        app: eeg-app
        component: epilepsy-prediction${APPENDSTRING}
    spec:
      containers:
      - name: epilepsy-prediction
        image: fberton98/epilepsy_prediction:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: epilepsy-prediction-service
  labels:
    app: eeg-app
    component: epilepsy-prediction${APPENDSTRING}
spec:
  selector:
    app: eeg-app
    component: epilepsy-prediction${APPENDSTRING}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer