apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-heartbeat-endpoint-deployment
spec:
  selector:
    matchLabels:
      app: eeg-app
      component: new-heartbeat-endpoint
  template:
    metadata:
      labels:
        app: eeg-app
        component: new-heartbeat-endpoint
    spec:
      containers:
      - name: new-heartbeat-endpoint
        image: fberton98/new_heartbeata_endpoint:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: new-heartbeat-endpoint-service
  labels:
    app: eeg-app
    component: new-heartbeat-endpoint
spec:
  selector:
    app: eeg-app
    component: new-heartbeat-endpoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: new-heartbeat-endpoint-hpa
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-heartbeat-endpoint-deployment