apiVersion: apps/v1
kind: Deployment
metadata:
  name: healt-center-web-page-deployment
spec:
  selector:
    matchLabels:
      app: eeg-app
      component: healt-center-web-page
  template:
    metadata:
      labels:
        app: eeg-app
        component: healt-center-web-page
    spec:
      containers:
      - name: healt-center-web-page
        image: fberton98/healt_center_web_page:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: healt-center-web-page-service
  labels:
    app: eeg-app
    component: healt-center-web-page
spec:
  selector:
    app: eeg-app
    component: healt-center-web-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
kind: HorizontalPodAutoscaler
metadata:
  name: healt-center-web-page-hpa
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: healt-center-web-page-deployment