name: Daily test

on:
  schedule:
    - cron: '20 12 * * *'  # Esegui ogni giorno alle 12:13 UTC
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ambiente di test
        run: |
          echo "Setup dell'ambiente di test"  # Comandi reali qui

      - name: Esegui i test
        run: |
          echo "Esecuzione dei test"  # Inserisci qui i comandi di test
