name: Dayly test

on:
  schedule:
    - cron: '13 12 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ambiente di test
        run: |

      - name: Esegui i test
        run: |
