name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Run SSH Commands
      run: |
        echo "${{ secrets.PASSWORD }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd k8_healtcare_cluster/_2_services/healt_center_web_page/docker
          docker build -t fberton98/healt_center_web_page:latest .
          docker push fberton98/healt_center_web_page:latest
          kubectl set image deployment/healt-center-web-page-deployment healt-center-web-page=fberton98/healt_center_web_page:latest
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PASSWORD }}
