name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -f _2_services/healt_center_web_page/docker -t fberton98/healt_center_web_page:latest .

    - name: Push Docker image
      run: docker fberton98/healt_center_web_page:latest

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Esegui comandi sulla VM Xubuntu
      env:
        SSH_USER: 'studente'
        SSH_PASSWORD: 'studente'
        SSH_HOST: '0.tcp.eu.ngrok.io'
        SSH_PORT: '11044'
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
          cd k8_healtcare_cluster
          kubectl set image deployment/healt-center-web-page-deployment healt-center-web-page=fberton98/healt_center_web_page:latest
        EOF