name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: SSH and deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PASSWORD }}
        script: |
          cd k8_healtcare_cluster/_2_services/healt_center_web_page/docker
          docker build -t fberton98/healt_center_web_page:latest .
          docker push fberton98/healt_center_web_page:latest
          kubectl set image deployment/healt-center-web-page-deployment healt-center-web-page=fberton98/healt_center_web_page:latest
